### ISSUE TITLE
[Suggestion for new mods] old ideas forgoten

### ISSUE THREAD

**Issue by DeRp-MaSte5** [Bletch1971/TektopiaCommon#1]
so you know how in the first tangotek video theres a list of ideas he has for new villagers? like example the alchemest which would brew potions to better each villager or the mage which would cast spells to defend the village. like the archer would be able to help the guards defend the village. (if you do, make the arrows try to not hit the guards) i feel like if you add these, tektopia would feel a little more, completed to say the least. oh and i have a idea just on my own, how about a fisherman villager?

**Comment by Bletch1971** [comment]
The way that Tango wrote the Tektopia mod, he hardcoded the structures and professions. What this means is that trying to create new villager or structure types is not possible without a lot of hacky code, and then maybe not possible. I do not feel comfortable implementing this hacky code as it might break the game, or corrupt work saves.

I was thinking of an archer as well, but would require a different type of guard and someone to make the bows and arrows.
As for the fisherman, you would need a new villager type, structure (fishing hut, near water), and someone to cook the fish, and add fish to the food that villagers can eat.
Alchemist would also be a new villager type, along with a structure and a brewing stand that they could create the potions. Then would need to add the potions to the other villagers for use.

I have also taken a short break from developing mods for Tektopia as I spent quite a bit of time developing the other 3 mods, and they are hardly being used. I might come back to it later on if there is intrerest, but at this stage, I think Tektopia is slowly dying and interest is being lost.

It is hard to keep a mod alive when the original developer (Tango) seems to have given up on it.

**Comment by DeRp-MaSte5** [comment]
fair enough
